version: '3.8'
services:
  mongodb:
    image: mongo:6
    volumes:
      - mydbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: erick
      MONGO_INITDB_ROOT_PASSWORD: secret
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - 8088:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_USERNAME=erick
      - MONGODB_PASSWORD=secret
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mydbdata:
  logs: